name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: sudo apt install build-essential mingw-w64
    - name: make
      run: make CROSS=i686-w64-mingw32-
    - name: upload
      uses: actions/upload-artifact@v2
      with:
        name: exe
        path: EJ2Esc.exe
